#!/usr/bin/env python3
"""Pool the latest-year salaries of two consecutive promotion cohorts and place Wallace in the pool.

Usage:
  python3 scripts/build_promotion_pool.py --year 2025

The pool is every research-stream, main-campus faculty member promoted from Associate
Professor to Professor in YEAR (cohort YEAR-1 -> YEAR) or in YEAR-1 (cohort YEAR-2 -> YEAR-1),
with their YEAR salary. The earlier cohort must still be listed as Professor in YEAR.
Wallace's YEAR figure is his annualized base (VALIDATION in promotion_cohort.py).

Outputs (no names):
- analysis_output/promotion_pool_<year>.csv   (rank, salary, cohort, subject)
- analysis_output/promotion_pool_<year>.tex   (LaTeX macros for promotion_report.tex)
- data/private/sphs_comparison_<year>.tex     (gitignored)
- data/review/health_matches.csv              (gitignored: surname-only roster matches to check)

The SPHS comparison uses the faculty list in data/sphs.csv. It reports only counts: how many
other SPHS faculty have the title Professor in YEAR, and how many of them were paid more than
Wallace's annualized base. No colleague's salary is reported.

The Faculty of Health subset uses data/private/health_roster.csv (scripts/build_health_roster.py).
A pool member is in Health when surname and first given name match a roster name. A match on
surname only is not counted; it goes to data/review/health_matches.csv.
"""

from __future__ import annotations

import argparse
import csv

import promotion_cohort as pc

OUT_DIR = pc.ROOT / "analysis_output"
PRIVATE_DIR = pc.ROOT / "data" / "private"
SPHS_LIST = pc.ROOT / "data" / "sphs.csv"
HEALTH_ROSTER = PRIVATE_DIR / "health_roster.csv"
# Base salary adjustment that the report requests, by year.
REQUESTED_ADJUSTMENT = {2025: 30_000.0}
UNIT_MANIFEST = pc.ROOT / "data" / "raw" / "unit_manifest.csv"
HEALTH_REVIEW = pc.ROOT / "data" / "review" / "health_matches.csv"


def find_one(index: dict, record: pc.Record) -> pc.Record | None:
    """The single record in index for this person, using middle initials if the name is not unique."""
    matches = index.get(record.key, [])
    if len(matches) > 1:
        matches = [r for r in matches if r.full_key == record.full_key]
    return matches[0] if len(matches) == 1 else None


def money(x: float) -> str:
    return f"\\${x:,.0f}".replace(",", "{,}")


def write_macros(path, macros: dict[str, str], year: int, script: str = "build_promotion_pool.py") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write(f"% Generated by scripts/{script} --year {year}. Do not edit.\n")
        for name, value in macros.items():
            f.write(f"\\newcommand{{\\{name}}}{{{value}}}\n")


def group_paid(records: list[pc.Record], rank: str, stream: str) -> list[float]:
    return [r.paid for r in records if r.cls.rank == rank and r.cls.stream == stream and pc.is_main_campus_regular(r.cls)]


def count_paid_more(records: list[pc.Record], rank: str, stream: str, base: float) -> tuple[int, int]:
    """Number of main-campus records with this rank and stream, and how many were paid more than base."""
    group = group_paid(records, rank, stream)
    return len(group), sum(paid > base for paid in group)


def quartile_check(values: list[float]) -> dict[str, tuple[float, float, bool]]:
    """Inclusive-method Q1, median and Q3 with a disclosure check.

    For each statistic: (1-based position in the sorted data, value, shown). A statistic is
    shown only if it falls between two different salaries, so it is no one person's salary.
    """
    ordered = sorted(values)
    result = {}
    for name, p in (("Q1", 0.25), ("median", 0.5), ("Q3", 0.75)):
        h = (len(ordered) - 1) * p
        low = int(h)
        frac = h - low
        if frac == 0:
            result[name] = (h + 1, ordered[low], False)
        else:
            value = ordered[low] + frac * (ordered[low + 1] - ordered[low])
            result[name] = (h + 1, value, ordered[low] != ordered[low + 1])
    return result


def band_macros(prefix: str, values: list[float]) -> dict[str, str]:
    """Q1 and Q3 band edges for a figure. Stops if either edge is one person's salary."""
    check = quartile_check(values)
    for name, (position, _, shown) in check.items():
        print(f"{prefix} (n = {len(values)}): {name} at position {position:g}: "
              f"{'shown (between two different salaries)' if shown else 'NOT shown (one person or equal neighbours)'}")
    for name in ("Q1", "Q3"):
        if not check[name][2]:
            raise SystemExit(f"{prefix} {name} equals one person's salary; the band cannot be drawn.")
    return {f"{prefix}QOneRaw": f"{check['Q1'][1]:.0f}", f"{prefix}QThreeRaw": f"{check['Q3'][1]:.0f}"}


REQUEST_SENTENCES = {
    "near": "The salary that I request is near the lower edge of the middle 50\\% of SPHS Professors.",
    "below": "The salary that I request is below the middle 50\\% of SPHS Professors.",
    "above": "",
}


def request_position(target: float, q1: float, margin: float = 5_000.0) -> str:
    """'near' if target is within margin of q1, else 'below' or 'above'."""
    if abs(target - q1) <= margin:
        return "near"
    return "below" if target < q1 else "above"


def sphs_macros(curr_year: list[pc.Record], base: float, target: float | None = None) -> dict[str, str]:
    """Only counts, so that no SPHS colleague can be identified."""
    with SPHS_LIST.open(encoding="utf-8") as f:
        sphs_keys = {pc.name_key(r["Surname"], r["Given name"]) for r in csv.DictReader(f)}
    sphs_keys.discard(pc.SUBJECT)

    index = pc.index_by_key(curr_year)
    records = [index[k][0] for k in sphs_keys if len(index.get(k, [])) == 1]
    n_prof, n_prof_above = count_paid_more(records, "Professor", "research", base)
    n_assoc, n_assoc_above = count_paid_more(records, "Associate", "research", base)
    return {
        "SphsNProf": str(n_prof),
        "SphsNProfAbove": str(n_prof_above),
        "SphsNAssoc": str(n_assoc),
        "SphsNAssocAbove": str(n_assoc_above),
    } | band_macros("SphsAssoc", group_paid(records, "Associate", "research")) \
      | band_macros("SphsProf", group_paid(records, "Professor", "research")) \
      | sphs_request_macros(group_paid(records, "Professor", "research"), target)


def sphs_request_macros(professors: list[float], target: float | None) -> dict[str, str]:
    if target is None:
        return {}
    q1 = quartile_check(professors)["Q1"][1]
    position = request_position(target, q1)
    print(f"Requested salary vs SPHS Professor Q1: {target - q1:+,.0f} ({position})")
    return {"SphsRequestSentence": REQUEST_SENTENCES[position]}


def roster_match(record: pc.Record, roster: list[list[str]]) -> str:
    """'yes' for surname + first given name, 'surname' for surname only, '' for no match."""
    surname = pc.normalize_name_part(record.surname).split()
    given = pc.normalize_given(record.given).split()[:1]
    result = ""
    for tokens in roster:
        if all(t in tokens for t in surname):
            if given and tokens[0] == given[0]:
                return "yes"
            result = "surname"
    return result


def health_macros(pool: list[tuple[float, str, bool, pc.Record]], base: float) -> dict[str, str]:
    """Only counts, so that no colleague can be identified."""
    with HEALTH_ROSTER.open(encoding="utf-8") as f:
        roster = [pc.normalize_name_part(r["name"]).split() for r in csv.DictReader(f)]
    health, review = [], []
    for salary, cohort, is_subject, record in pool:
        match = "yes" if is_subject else roster_match(record, roster)
        if match == "yes":
            health.append(salary)
        elif match == "surname":
            review.append({"reason": "surname matches Health roster; given name does not",
                           "name": record.name, "title": record.title, "cohort": cohort})
    HEALTH_REVIEW.parent.mkdir(parents=True, exist_ok=True)
    with HEALTH_REVIEW.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["reason", "name", "title", "cohort"])
        writer.writeheader()
        writer.writerows(review)
    rank, _ = pc.position(health, base)
    print(f"Faculty of Health: {len(health)} in pool, Wallace rank {rank}; {len(review)} rows to check")
    return {
        "HealthN": str(len(health)),
        "HealthRank": str(rank),
        "HealthNAbove": str(sum(s > base for s in health)),
        "HealthNReview": str(len(review)),
        "HealthRosterDate": min(r["retrieved"] for r in csv.DictReader(UNIT_MANIFEST.open(encoding="utf-8"))),
    }


def request_macros(base: float, adjustment: float, q1: float, median: float) -> dict[str, str]:
    target = base + adjustment
    print(f"Request: ${base:,.2f} + ${adjustment:,.0f} = ${target:,.2f} ({100 * adjustment / base:.1f}% of base); "
          f"between lower quartile and median: {q1 < target < median}")
    return {
        "RequestAdj": money(adjustment),
        "RequestTarget": money(target),
        "RequestTargetRaw": f"{target:.0f}",
        "RequestPct": f"{100 * adjustment / base:.0f}",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--year", type=int, required=True)
    args = parser.parse_args()
    year = args.year
    base = pc.VALIDATION[year]["subject_annualized_base"]

    y0, y1, y2 = (pc.load_year(y) for y in (year - 2, year - 1, year))
    earlier = pc.build_cohorts(y0, y1).cohorts["research"]
    current = pc.build_cohorts(y1, y2).cohorts["research"]
    index = pc.index_by_key(y2)

    pool: list[tuple[float, str, bool, pc.Record]] = []
    earlier_kept = 0
    for _, b in earlier:
        c = find_one(index, b)
        if c and c.cls.rank == "Professor" and pc.is_main_campus_regular(c.cls):
            pool.append((c.paid, str(year - 1), False, c))
            earlier_kept += 1
    subject_prev = None
    for a, b in current:
        is_subject = a.key == pc.SUBJECT
        if is_subject:
            subject_prev = a.paid
        pool.append((base if is_subject else b.paid, str(year), is_subject, b))
    if subject_prev is None:
        raise SystemExit("Wallace is not in the current cohort.")

    salaries = [s for s, _, _, _ in pool]
    rank, pct = pc.position(salaries, base)
    _, q1, median, q3, _ = pc.five_numbers(salaries)
    current_salaries = [s for s, c, _, _ in pool if c == str(year)]
    rank_current, _ = pc.position(current_salaries, base)
    prev_values = [a.paid for a, _ in current]
    rank_prev, _ = pc.position(prev_values, subject_prev)
    below = sorted(s for s in salaries if s < base)

    pool.sort(key=lambda p: p[0])
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with (OUT_DIR / f"promotion_pool_{year}.csv").open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["rank_ascending", "salary", "cohort", "subject"])
        for i, (s, c, is_subject, _) in enumerate(pool, start=1):
            writer.writerow([i, f"{s:.2f}", c, int(is_subject)])

    macros = {
        "PoolYear": str(year),
        "PoolPrevYear": str(year - 1),
        "PoolEarlierYear": str(year - 2),
        "PoolN": str(len(salaries)),
        "PoolNCurrent": str(len(current)),
        "PoolNEarlier": str(len(earlier)),
        "PoolNEarlierKept": str(earlier_kept),
        "PoolQOne": money(q1),
        "PoolMedian": money(median),
        "PoolQThree": money(q3),
        "PoolMedianRaw": f"{median:.0f}",
        "PoolQOneRaw": f"{q1:.0f}",
        "PoolQThreeRaw": f"{q3:.0f}",
        "SubjectBase": money(base),
        "SubjectBaseRaw": f"{base:.0f}",
        "SubjectRank": str(rank),
        "SubjectRankAscending": str(len(salaries) - rank + 1),
        "SubjectPercentile": f"{pct:.0f}",
        "SubjectRankCurrent": str(rank_current),
        "SubjectRankPrev": str(rank_prev),
        "SubjectPrevPaid": money(subject_prev),
        "NumBelowSubject": str(len(below)),
        "GapMedian": money(median - base),
        "GapMedianPct": f"{100 * (median - base) / median:.0f}",
        "GapQOne": money(q1 - base),
        "GapQOnePct": f"{100 * (q1 - base) / base:.0f}",
        "GapMedianPctOfBase": f"{100 * (median - base) / base:.0f}",
    }
    if year in REQUESTED_ADJUSTMENT:
        macros |= request_macros(base, REQUESTED_ADJUSTMENT[year], q1, median)
    write_macros(OUT_DIR / f"promotion_pool_{year}.tex", macros, year)
    target = base + REQUESTED_ADJUSTMENT[year] if year in REQUESTED_ADJUSTMENT else None
    write_macros(PRIVATE_DIR / f"sphs_comparison_{year}.tex",
                 sphs_macros(y2, base, target) | health_macros(pool, base), year)

    print(f"Pool n = {len(salaries)} ({len(current)} promoted {year}, {earlier_kept} of {len(earlier)} promoted {year - 1})")
    print(f"Wallace annualized base ${base:,.2f}: rank {rank} of {len(salaries)} (1 = highest), percentile {pct:.0f}")
    print(f"Pool quartiles: Q1 ${q1:,.0f}, median ${median:,.0f}, Q3 ${q3:,.0f}")
    print(f"Wrote analysis_output/promotion_pool_{year}.csv and .tex, data/private/sphs_comparison_{year}.tex")


if __name__ == "__main__":
    main()
